[package]
name = "monkey-rust"
version = "0.1.0"
authors = ["Waqar Ahmed <waahm7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = "*"